// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"
)

type Querier interface {
	CreateDevice(ctx context.Context, arg *CreateDeviceParams) (*Device, error)
	CreateLocation(ctx context.Context, arg *CreateLocationParams) (*Location, error)
	CreateSensorAir(ctx context.Context, arg *CreateSensorAirParams) (*SensorAir, error)
	DeleteDevice(ctx context.Context, id string) (*Device, error)
	DeleteLocation(ctx context.Context, id string) (*Location, error)
	DeleteSensorAir(ctx context.Context, id string) (*SensorAir, error)
	GetDevice(ctx context.Context, id string) (*Device, error)
	GetDevices(ctx context.Context) ([]*Device, error)
	GetLocation(ctx context.Context, id string) (*Location, error)
	GetLocations(ctx context.Context) ([]*Location, error)
	GetSensorAir(ctx context.Context, id string) (*SensorAir, error)
	GetSensorAirs(ctx context.Context) ([]*SensorAir, error)
	UpdateDevice(ctx context.Context, arg *UpdateDeviceParams) (*Device, error)
	UpdateLocation(ctx context.Context, arg *UpdateLocationParams) (*Location, error)
	UpdateSensorAir(ctx context.Context, arg *UpdateSensorAirParams) (*SensorAir, error)
}

var _ Querier = (*Queries)(nil)
