services:
  curiosity:
    image: curiosity
    build: ./curiosity
    expose:
      - "8080"
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - HOST=0.0.0.0
  hardwire:
    image: hardwire
    build: ./hardwire
  transporter:
    image: transporter
    build: ./transporter
    expose:
      - "3000"