services:
  curiosity:
    image: curiosity
    build: ./curiosity
    expose:
      - "8080"
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - HOST=0.0.0.0
  hardwire:
    image: hardwire
    build: ./hardwire
  transporter:
    image: transporter
    build: ./transporter
    expose:
      - "3000"
  mosquitto:
    image: eclipse-mosquitto:latest
    expose:
      - 1883
    ports:
      - "1883:1883"
    volumes:
      - "./mosquitto.conf:/mosquitto/config/mosquitto.conf"