version:  '3'
tasks:
  start: 
    cmds:
      -  docker compose build
      -  docker compose up -d
  stop: 
    cmds:
      -  docker compose down --remove-orphans
  logs: 
    cmds:
      -  docker compose logs -f
  seed:
    cmds:
      -  docker run -it --rm --network=host -e PGPASSWORD=root postgres psql -h localhost -U root -d home_engine -a -f ./bengine/seed.sql
