version:  '3'
tasks:
  start: 
    cmds:
      -  docker compose build
      -  docker compose up -d
  stop: 
    cmds:
      -  docker compose down --remove-orphans
  logs: 
    cmds:
      -  docker compose logs -f