version:  '3'
tasks:
  start: 
    cmds:
      -  docker compose build
      -  docker compose up -d
  stop: 
    cmds:
      -  docker compose down --remove-orphans
  db: 
    cmds:
      -  docker compose stop timescaledb
      -  docker compose up -d timescaledb
  mqtt:
    cmds:
      -  docker compose stop mosquitto
      -  docker compose up -d mosquitto
  logs: 
    cmds:
      -  docker compose logs -f
