services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto_mqtt
    volumes:
      - ./mqtt-broker/mosquitto.conf:/mosquitto/config/mosquitto.conf
    ports:
      - 1883:1883
      - 9001:9001

volumes:
  data: ~