services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto_mqtt
    volumes:
      - ./mqtt-broker/mosquitto.conf:/mosquitto/config/mosquitto.conf
    ports:
      - 1883:1883
      - 9001:9001
  mongo:
    image: mongo:latest
    container_name: mongo_db
    volumes:
      - ./mongo-db:/data/db
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mqtt
      - MONGO_INITDB_ROOT_PASSWORD=mqtt
      - MONGO_INITDB_DATABASE=mqtt

volumes:
  data: ~